// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFh88369xjNBEYBLuO_Z4vqdj8gjvVhg8',
    appId: '1:727536888892:web:cfe61069db6d41ae686739',
    messagingSenderId: '727536888892',
    projectId: 'voiceapp-a57e3',
    authDomain: 'voiceapp-a57e3.firebaseapp.com',
    storageBucket: 'voiceapp-a57e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLrdStGEh6ihii12kOYj64JdmvzUi4cxU',
    appId: '1:727536888892:android:cb5833604c8dd9f7686739',
    messagingSenderId: '727536888892',
    projectId: 'voiceapp-a57e3',
    storageBucket: 'voiceapp-a57e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQvwdavwx4K4j_QA9AhyugYjTU3CJHUKw',
    appId: '1:727536888892:ios:706accab21096d0f686739',
    messagingSenderId: '727536888892',
    projectId: 'voiceapp-a57e3',
    storageBucket: 'voiceapp-a57e3.appspot.com',
    iosBundleId: 'com.example.micapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQvwdavwx4K4j_QA9AhyugYjTU3CJHUKw',
    appId: '1:727536888892:ios:706accab21096d0f686739',
    messagingSenderId: '727536888892',
    projectId: 'voiceapp-a57e3',
    storageBucket: 'voiceapp-a57e3.appspot.com',
    iosBundleId: 'com.example.micapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFh88369xjNBEYBLuO_Z4vqdj8gjvVhg8',
    appId: '1:727536888892:web:8ec845c62f446a6b686739',
    messagingSenderId: '727536888892',
    projectId: 'voiceapp-a57e3',
    authDomain: 'voiceapp-a57e3.firebaseapp.com',
    storageBucket: 'voiceapp-a57e3.appspot.com',
  );

}